[tool.poetry]
name = "gpt-verse"
version = "0.1.0"
description = ""
authors = ["Valerio Domenici"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langgraph = "^0.0.44"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
